name 'puppet-opendj'
version '1.0.0'
source ''
author ''
license 'Apache License, Version 2.0'
summary 'puppet-opendj'
description 'Installs and configures opendj'
project_page ''
dependency 'puppetlabs/stdlib', '>= 3.2.0'
